version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: hotel-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: hotel-rabbitmq
    restart: unless-stopped
    ports:
      - "5672:5672"   # protocolo AMQP (lo usan los microservicios)
      - "15672:15672" # panel web de administración
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  mongo_data:
  rabbitmq_data:
